Add information about how to build from source
Directly using git repository or zip file provided by github to build can encounter errors:
'''Z3Interface.cpp:166:14: error: ‘mod’ is not a member of ‘z3’'''

Guidance about cloning git repository is provided above so it is misleading and may make many people directly use the git repository to build.

Therefore, additional information is added in the front of Section Command-Line Build to clarify the source code to use.